export const homeCopy = {
  pt: {
    available: "DISPONÍVEL PARA NOVOS DESAFIOS",
    titleA: "Transformo ideias",
    titleBPrefix: "em",
    titleBHighlight: "produtos digitais",
    subtitle:
      "Desenvolvo aplicações completas, automações e experiências com IA que geram valor real para negócios e pessoas.",
    primary: "Ver projetos",
    secondary: "Currículo",
    lab: "Lab interativo com ranking real",
    featured: "PROJETO EM DESTAQUE",
    previous: "Anterior",
    next: "Próximo",
    viewCase: "Ver estudo",
    openSite: "Abrir site",
    scroll: "ROLE PARA EXPLORAR",
    capability: [
      ["Aplicações completas", "Produtos web escaláveis", "code"],
      ["Automações", "Fluxos que economizam tempo", "zap"],
      ["IA aplicada", "Inteligência com propósito", "brain"],
      ["Dados e métricas", "Decisões mais claras", "line-chart"],
      ["Segurança", "Proteção desde a base", "shield"],
    ],
    capabilityMobile: [
      ["Aplicações", "Produtos web", "code"],
      ["Automações", "Fluxos inteligentes", "zap"],
      ["IA", "Uso prático", "brain"],
      ["Dados", "Decisões claras", "line-chart"],
      ["Segurança", "Base protegida", "shield"],
    ],
    projectsEyebrow: "PROJETOS EM DESTAQUE",
    projectsTitle: "Produtos construídos do conceito à entrega.",
    projectsIntro: "Projetos reais com contexto, stack e decisão técnica.",
    stackEyebrow: "STACK APLICADA",
    stackTitle: "Ferramentas que trabalham juntas.",
    stackIntro: "Tecnologias escolhidas com critério para resolver problemas reais.",
    processEyebrow: "PROCESSO DE CONSTRUÇÃO",
    processTitle: "Como eu trabalho.",
    arcadeEyebrow: "DEVELOPER ARCADE",
    arcadeTitle: "Um lab com ranking real.",
    arcadeIntro: "Desafios técnicos curtos, jogáveis no navegador, com leaderboard ao vivo.",
    aboutEyebrow: "SOBRE",
    aboutTitle: "Construo produtos que funcionam de verdade.",
    aboutText: "Sou desenvolvedor Full Stack focado em produtos web, automações, dados e IA aplicada.",
    finalTitle: "Vamos construir algo útil?",
    finalSubtitle: "Se você tem uma ideia, um produto em andamento ou um problema que merece uma solução bem feita — vamos conversar.",
    allProjects: "Ver todos",
    openLab: "Entrar no Arcade",
    contact: "Entrar em contato",
    stackDetails: {
      next: "App Router, RSC e edge",
      react: "Interfaces componíveis",
      typescript: "Type-safety ponta a ponta",
      tailwind: "Design system rápido",
      supabase: "Auth, dados e realtime",
      prisma: "ORM type-safe",
      postgres: "Banco relacional sólido",
      node: "APIs e serviços",
      python: "Automação e IA",
      go: "Serviços de performance",
      rabbitmq: "Eventos e mensageria",
      vite: "DX moderno",
    },
    processSteps: [
      ["Descoberta", "Entender o problema, o público e o contexto antes de qualquer linha de código.", "compass"],
      ["Arquitetura", "Decisões técnicas claras: dados, fluxos, integrações e trade-offs.", "layers"],
      ["Interface", "Design system funcional, foco em clareza e velocidade de iteração.", "palette"],
      ["Entrega", "Deploy contínuo, observabilidade e iteração baseada em uso real.", "rocket"],
    ],
    arcadeLeaderboard: "Top jogadores",
    arcadeLive: "ao vivo",
    arcadeYou: "você?",
    aboutStats: [
      ["6+", "Produtos em produção"],
      ["5+", "Anos construindo software"],
      ["100%", "Foco em entrega real"],
    ],
  },
  en: {
    available: "AVAILABLE FOR NEW CHALLENGES",
    titleA: "I turn ideas",
    titleBPrefix: "into",
    titleBHighlight: "digital products",
    subtitle:
      "I build full-stack applications, automations and AI experiences that create real value for businesses and people.",
    primary: "View projects",
    secondary: "Resume",
    lab: "Interactive Lab with real ranking",
    featured: "FEATURED PROJECT",
    previous: "Previous",
    next: "Next",
    viewCase: "View case",
    openSite: "Open site",
    scroll: "SCROLL TO EXPLORE",
    capability: [
      ["Full applications", "Scalable web products", "code"],
      ["Automations", "Flows that save time", "zap"],
      ["Applied AI", "Purposeful intelligence", "brain"],
      ["Data and metrics", "Clearer decisions", "line-chart"],
      ["Security", "Protection from the base", "shield"],
    ],
    capabilityMobile: [
      ["Apps", "Web products", "code"],
      ["Automation", "Smart flows", "zap"],
      ["AI", "Practical use", "brain"],
      ["Data", "Clear decisions", "line-chart"],
      ["Security", "Protected base", "shield"],
    ],
    projectsEyebrow: "FEATURED PROJECTS",
    projectsTitle: "Products built from concept to delivery.",
    projectsIntro: "Real projects with context, stack and technical decisions.",
    stackEyebrow: "APPLIED STACK",
    stackTitle: "Tools that work together.",
    stackIntro: "Technologies selected carefully to solve real problems.",
    processEyebrow: "BUILD PROCESS",
    processTitle: "How I work.",
    arcadeEyebrow: "DEVELOPER ARCADE",
    arcadeTitle: "A lab with real ranking.",
    arcadeIntro: "Short technical challenges, playable in the browser, with a live leaderboard.",
    aboutEyebrow: "ABOUT",
    aboutTitle: "I build products that actually work.",
    aboutText: "I am a Full Stack developer focused on web products, automations, data and applied AI.",
    finalTitle: "Let’s build something useful?",
    finalSubtitle: "If you have an idea, a product in progress or a problem that deserves a well-built solution — let’s talk.",
    allProjects: "View all",
    openLab: "Enter Arcade",
    contact: "Contact",
    stackDetails: {
      next: "App Router, RSC and edge",
      react: "Composable interfaces",
      typescript: "End-to-end type safety",
      tailwind: "Fast design system",
      supabase: "Auth, data and realtime",
      prisma: "Type-safe ORM",
      postgres: "Solid relational database",
      node: "APIs and services",
      python: "Automation and AI",
      go: "Performance services",
      rabbitmq: "Events and messaging",
      vite: "Modern DX",
    },
    processSteps: [
      ["Discovery", "Understanding the problem, audience and context before any line of code.", "compass"],
      ["Architecture", "Clear technical decisions: data, flows, integrations and trade-offs.", "layers"],
      ["Interface", "Functional design system focused on clarity and iteration speed.", "palette"],
      ["Delivery", "Continuous deployment, observability and iteration based on real usage.", "rocket"],
    ],
    arcadeLeaderboard: "Top players",
    arcadeLive: "live",
    arcadeYou: "you?",
    aboutStats: [
      ["6+", "Products in production"],
      ["5+", "Years building software"],
      ["100%", "Focus on real delivery"],
    ],
  },
} as const;
