import type { Skill } from "@/types/portfolio";

export const skills: Skill[] = [
  { name: "JavaScript", category: "front" },
  { name: "TypeScript", category: "front" },
  { name: "HTML5", category: "front" },
  { name: "CSS3", category: "front" },
  { name: "React", category: "front" },
  { name: "Next.js", category: "front" },
  { name: "Tailwind CSS", category: "front" },
  { name: "UI Libraries", category: "front" },
  { name: "Node.js", category: "back" },
  { name: "Python", category: "back" },
  { name: "REST APIs", category: "back" },
  { name: "JWT", category: "back" },
  { name: "OAuth", category: "back" },
  { name: "MySQL", category: "back" },
  { name: "PostgreSQL", category: "back" },
  { name: "MongoDB", category: "back" },
  { name: "Prisma", category: "back" },
  { name: "Supabase", category: "back" },
  { name: "Git", category: "devops" },
  { name: "GitHub", category: "devops" },
  { name: "Docker", category: "devops" },
  { name: "AWS", category: "devops" },
  { name: "CI/CD", category: "devops" },
  { name: "Vercel", category: "devops" },
  { name: "Scrum", category: "other" },
  { name: "AI Tools", category: "other" },
  { name: "LLMs", category: "other" },
  { name: "Codex", category: "other" },
];
