import type { LabGameId, Locale } from "@/types/portfolio";

export type LabGameDescriptor = {
  controls: Record<Locale, string>;
  description: Record<Locale, string>;
  id: LabGameId;
  shortLabel: string;
  title: string;
};

export const labGames: LabGameDescriptor[] = [
  {
    controls: {
      pt: "Espaço, ↑ ou toque",
      en: "Space, ↑ or tap",
    },
    description: {
      pt: "Atravesse um pipeline em aceleração, desviando de falhas de build, memória e rede.",
      en: "Cross an accelerating pipeline while avoiding build, memory, and network failures.",
    },
    id: "runtime",
    shortLabel: "RUN",
    title: "Runtime Runner",
  },
  {
    controls: {
      pt: "Setas ou swipe",
      en: "Arrows or swipe",
    },
    description: {
      pt: "Colete recursos, preserve suas vidas e encontre o caminho seguro até o deploy.",
      en: "Collect resources, preserve your lives, and find the safe path to deployment.",
    },
    id: "bug-maze",
    shortLabel: "MAZE",
    title: "Bug Maze",
  },
  {
    controls: {
      pt: "Setas ou swipe",
      en: "Arrows or swipe",
    },
    description: {
      pt: "Capture tokens, aumente o combo e sobreviva aos bugs em uma grade dinâmica.",
      en: "Capture tokens, build your combo, and survive bugs on a dynamic grid.",
    },
    id: "code-snake",
    shortLabel: "SNAKE",
    title: "Code Snake",
  },
  {
    controls: {
      pt: "Setas, espaço ou swipe",
      en: "Arrows, space, or swipe",
    },
    description: {
      pt: "Organize módulos de software, compile linhas e mantenha a build sob controle.",
      en: "Organize software modules, compile lines, and keep the build under control.",
    },
    id: "stack-tetris",
    shortLabel: "STACK",
    title: "Stack Tetris",
  },
];

export const labV2Copy = {
  pt: {
    eyebrow: "DEVELOPER ARCADE",
    title: "Jogue. Aprenda. Entre no ranking.",
    intro: "Quatro desafios técnicos rápidos para explorar lógica, reflexo e resolução de problemas diretamente no navegador.",
    live: "Arcade online",
    persistent: "Score persistente",
    uniqueRanking: "Ranking por jogador",
    playerEyebrow: "SEU JOGADOR",
    playerTitle: "Identidade no Arcade",
    playerText: "Escolha um alias curto. Seu melhor resultado em cada jogo é o que vale no ranking.",
    aliasLabel: "Alias",
    aliasPlaceholder: "Ex: Álvaro Dev",
    saveAlias: "Salvar",
    savingAlias: "Salvando...",
    aliasSaved: "Alias atualizado.",
    aliasError: "Não foi possível atualizar o alias agora.",
    anonymous: "Anonymous Dev",
    sessionScore: "Score da sessão",
    completedGames: "Jogos concluídos",
    gamesEyebrow: "ESCOLHA SUA ARENA",
    gamesTitle: "Quatro jogos. Um melhor score por arena.",
    gamesText: "Abra um jogo, conclua a rodada e acompanhe sua evolução sem sair da página.",
    openGame: "Jogar agora",
    activeGame: "Arena ativa",
    closeGame: "Fechar arena",
    restartGame: "Reiniciar rodada",
    switchGame: "Trocar jogo",
    controls: "Controles",
    bestScore: "Melhor score",
    position: "Posição",
    noScore: "Ainda não jogado",
    focusEyebrow: "MODO FOCO",
    focusHint: "O score é enviado ao concluir a rodada. Apenas seu melhor resultado define sua posição.",
    submitting: "Registrando resultado...",
    submitted: "Resultado registrado",
    submitFailed: "Score local mantido. Tente novamente em outra rodada.",
    rankingEyebrow: "LEADERBOARD",
    rankingTitle: "Quem está no topo agora?",
    rankingText: "Selecione uma arena para ver os três melhores resultados e a sua posição atual.",
    topPlayers: "Top 3",
    yourResult: "Seu resultado",
    loading: "Preparando Arcade...",
    partial: "Parte do ranking está temporariamente indisponível. Os jogos continuam ativos.",
    loadError: "Não foi possível carregar os dados do ranking. Os jogos continuam disponíveis.",
    emptyRanking: "Nenhum score registrado nesta arena.",
    rankPrefix: "#",
    retry: "Tentar novamente",
  },
  en: {
    eyebrow: "DEVELOPER ARCADE",
    title: "Play. Learn. Enter the ranking.",
    intro: "Four fast technical challenges to explore logic, reflexes, and problem-solving directly in the browser.",
    live: "Arcade online",
    persistent: "Persistent score",
    uniqueRanking: "Player-based ranking",
    playerEyebrow: "YOUR PLAYER",
    playerTitle: "Arcade identity",
    playerText: "Choose a short alias. Your best result in each game is what counts on the leaderboard.",
    aliasLabel: "Alias",
    aliasPlaceholder: "E.g. Álvaro Dev",
    saveAlias: "Save",
    savingAlias: "Saving...",
    aliasSaved: "Alias updated.",
    aliasError: "The alias could not be updated right now.",
    anonymous: "Anonymous Dev",
    sessionScore: "Session score",
    completedGames: "Completed games",
    gamesEyebrow: "CHOOSE YOUR ARENA",
    gamesTitle: "Four games. One best score per arena.",
    gamesText: "Open a game, finish the round, and follow your progress without leaving the page.",
    openGame: "Play now",
    activeGame: "Active arena",
    closeGame: "Close arena",
    restartGame: "Restart run",
    switchGame: "Switch game",
    controls: "Controls",
    bestScore: "Best score",
    position: "Position",
    noScore: "Not played yet",
    focusEyebrow: "FOCUS MODE",
    focusHint: "Your score is submitted when the round ends. Only your best result defines your position.",
    submitting: "Saving result...",
    submitted: "Result saved",
    submitFailed: "Local score kept. Try again in another round.",
    rankingEyebrow: "LEADERBOARD",
    rankingTitle: "Who is on top right now?",
    rankingText: "Select an arena to view the three best results and your current position.",
    topPlayers: "Top 3",
    yourResult: "Your result",
    loading: "Preparing Arcade...",
    partial: "Part of the ranking is temporarily unavailable. The games remain active.",
    loadError: "Ranking data could not be loaded. The games remain available.",
    emptyRanking: "No score has been registered in this arena.",
    rankPrefix: "#",
    retry: "Try again",
  },
} as const;
