import type { LabGameId, Locale } from "@/types/portfolio";

export type LabGameDescriptor = {
  controls: Record<Locale, string>;
  description: Record<Locale, string>;
  id: LabGameId;
  shortLabel: string;
  title: string;
};

export const labGames: LabGameDescriptor[] = [
  {
    controls: {
      pt: "Espaço, ↑ ou toque",
      en: "Space, ↑ or tap",
    },
    description: {
      pt: "Atravesse um pipeline em aceleração, desviando de falhas de build, memória e rede.",
      en: "Cross an accelerating pipeline while avoiding build, memory, and network failures.",
    },
    id: "runtime",
    shortLabel: "RUN",
    title: "Runtime Runner",
  },
  {
    controls: {
      pt: "Setas ou swipe",
      en: "Arrows or swipe",
    },
    description: {
      pt: "Colete recursos, preserve suas vidas e encontre o caminho seguro até o deploy.",
      en: "Collect resources, preserve your lives, and find the safe path to deployment.",
    },
    id: "bug-maze",
    shortLabel: "MAZE",
    title: "Bug Maze",
  },
  {
    controls: {
      pt: "Setas ou swipe",
      en: "Arrows or swipe",
    },
    description: {
      pt: "Capture tokens, aumente o combo e sobreviva aos bugs em uma grade dinâmica.",
      en: "Capture tokens, build your combo, and survive bugs on a dynamic grid.",
    },
    id: "code-snake",
    shortLabel: "SNAKE",
    title: "Code Snake",
  },
  {
    controls: {
      pt: "Setas, espaço ou swipe",
      en: "Arrows, space, or swipe",
    },
    description: {
      pt: "Organize módulos de software, compile linhas e mantenha a build sob controle.",
      en: "Organize software modules, compile lines, and keep the build under control.",
    },
    id: "stack-tetris",
    shortLabel: "STACK",
    title: "Stack Tetris",
  },
];

export const labV2Copy = {
  pt: {
    eyebrow: "DEVELOPER ARCADE",
    title: "Quatro desafios. Um ranking.",
    intro: "Escolha uma arena, jogue uma rodada curta e acompanhe seu melhor resultado sem sair do portfólio.",
    live: "Arcade online",
    persistent: "Melhor score salvo",
    uniqueRanking: "Ranking por jogador",
    playerEyebrow: "SEU JOGADOR",
    playerTitle: "Perfil do Arcade",
    playerText: "Defina um alias curto. Só o seu melhor resultado em cada arena vale no ranking.",
    aliasLabel: "Alias",
    aliasPlaceholder: "Ex: Álvaro Dev",
    saveAlias: "Salvar",
    savingAlias: "Salvando...",
    aliasSaved: "Alias atualizado.",
    aliasError: "Não foi possível atualizar o alias agora.",
    anonymous: "Anonymous Dev",
    sessionScore: "Score da sessão",
    completedGames: "Jogos concluídos",
    gamesEyebrow: "ARENAS",
    gamesTitle: "Escolha e jogue.",
    gamesText: "Os quatro desafios ficam disponíveis aqui. Abra uma arena, conclua a rodada e volte para acompanhar score e posição.",
    openGame: "Jogar agora",
    activeGame: "Arena ativa",
    closeGame: "Fechar arena",
    restartGame: "Reiniciar rodada",
    switchGame: "Trocar jogo",
    controls: "Controles",
    bestScore: "Melhor score",
    position: "Posição",
    noScore: "Ainda não jogado",
    focusEyebrow: "MODO FOCO",
    focusHint: "O score é enviado ao concluir a rodada. Apenas seu melhor resultado define sua posição.",
    submitting: "Registrando resultado...",
    submitted: "Resultado registrado",
    submitFailed: "Score local mantido. Tente novamente em outra rodada.",
    rankingEyebrow: "LEADERBOARD",
    rankingTitle: "Top do Arcade.",
    rankingText: "Troque de arena para comparar o Top 3 com o seu melhor resultado atual.",
    topPlayers: "Top 3",
    liveRanking: "LIVE",
    yourResult: "Seu resultado",
    loading: "Preparando Arcade...",
    partial: "Parte do ranking está temporariamente indisponível. Os jogos continuam ativos.",
    loadError: "Não foi possível carregar os dados do ranking. Os jogos continuam disponíveis.",
    emptyRanking: "Nenhum score registrado nesta arena.",
    rankPrefix: "#",
    retry: "Tentar novamente",
  },
  en: {
    eyebrow: "DEVELOPER ARCADE",
    title: "Four challenges. One ranking.",
    intro: "Choose an arena, play a short round, and track your best result without leaving the portfolio.",
    live: "Arcade online",
    persistent: "Best score saved",
    uniqueRanking: "Player-based ranking",
    playerEyebrow: "YOUR PLAYER",
    playerTitle: "Arcade profile",
    playerText: "Set a short alias. Only your best result in each arena counts on the leaderboard.",
    aliasLabel: "Alias",
    aliasPlaceholder: "E.g. Álvaro Dev",
    saveAlias: "Save",
    savingAlias: "Saving...",
    aliasSaved: "Alias updated.",
    aliasError: "The alias could not be updated right now.",
    anonymous: "Anonymous Dev",
    sessionScore: "Session score",
    completedGames: "Completed games",
    gamesEyebrow: "ARENAS",
    gamesTitle: "Choose and play.",
    gamesText: "All four challenges stay available here. Open an arena, finish the round, and return to track score and position.",
    openGame: "Play now",
    activeGame: "Active arena",
    closeGame: "Close arena",
    restartGame: "Restart run",
    switchGame: "Switch game",
    controls: "Controls",
    bestScore: "Best score",
    position: "Position",
    noScore: "Not played yet",
    focusEyebrow: "FOCUS MODE",
    focusHint: "Your score is submitted when the round ends. Only your best result defines your position.",
    submitting: "Saving result...",
    submitted: "Result saved",
    submitFailed: "Local score kept. Try again in another round.",
    rankingEyebrow: "LEADERBOARD",
    rankingTitle: "Arcade top scores.",
    rankingText: "Switch arenas to compare the Top 3 with your current best result.",
    topPlayers: "Top 3",
    liveRanking: "LIVE",
    yourResult: "Your result",
    loading: "Preparing Arcade...",
    partial: "Part of the ranking is temporarily unavailable. The games remain active.",
    loadError: "Ranking data could not be loaded. The games remain available.",
    emptyRanking: "No score has been registered in this arena.",
    rankPrefix: "#",
    retry: "Try again",
  },
} as const;
