import type { LabGameId, Locale } from "@/types/portfolio";

export type LabGameDescriptor = {
  controls: Record<Locale, string>;
  description: Record<Locale, string>;
  id: LabGameId;
  shortLabel: string;
  title: string;
};

export const labGames: LabGameDescriptor[] = [
  {
    controls: {
      pt: "Espaço, ↑ ou toque",
      en: "Space, ↑ or tap",
    },
    description: {
      pt: "Atravesse um pipeline em aceleração, desviando de falhas de build, memória e rede.",
      en: "Cross an accelerating pipeline while avoiding build, memory, and network failures.",
    },
    id: "runtime",
    shortLabel: "RUN",
    title: "Runtime Runner",
  },
  {
    controls: {
      pt: "Setas ou swipe",
      en: "Arrows or swipe",
    },
    description: {
      pt: "Colete recursos, preserve suas vidas e encontre o caminho seguro até o deploy.",
      en: "Collect resources, preserve your lives, and find the safe path to deployment.",
    },
    id: "bug-maze",
    shortLabel: "MAZE",
    title: "Bug Maze",
  },
  {
    controls: {
      pt: "Setas ou swipe",
      en: "Arrows or swipe",
    },
    description: {
      pt: "Capture tokens, aumente o combo e sobreviva aos bugs em uma grade dinâmica.",
      en: "Capture tokens, build your combo, and survive bugs on a dynamic grid.",
    },
    id: "code-snake",
    shortLabel: "SNAKE",
    title: "Code Snake",
  },
  {
    controls: {
      pt: "Setas, espaço ou swipe",
      en: "Arrows, space, or swipe",
    },
    description: {
      pt: "Organize módulos de software, compile linhas e mantenha a build sob controle.",
      en: "Organize software modules, compile lines, and keep the build under control.",
    },
    id: "stack-tetris",
    shortLabel: "STACK",
    title: "Stack Tetris",
  },
];

export const labV2Copy = {
  pt: {
    eyebrow: "DEVELOPER ARCADE",
    title: "Developer Arcade",
    intro: "Quatro arenas rápidas para testar lógica, reflexo e consistência.",
    live: "Arcade online",
    persistent: "Melhor score salvo",
    uniqueRanking: "Ranking por jogador",
    playerEyebrow: "SEU JOGADOR",
    playerTitle: "Perfil do Arcade",
    playerText: "Seu alias identifica seus resultados nas quatro arenas.",
    aliasLabel: "Alias",
    aliasPlaceholder: "Ex: Álvaro Dev",
    saveAlias: "Salvar",
    savingAlias: "Salvando...",
    aliasSaved: "Alias atualizado.",
    aliasError: "Não foi possível atualizar o alias agora.",
    aliasRequired: "Digite um alias para continuar.",
    anonymous: "AN",
    noAlias: "Alias não definido",
    editAlias: "Editar",
    setAlias: "Definir alias",
    sessionScore: "Score da sessão",
    completedGames: "Jogos concluídos",
    bestPosition: "Melhor posição",
    gamesEyebrow: "ARENAS",
    gamesTitle: "Escolha uma arena.",
    gamesText: "Entre em um dos quatro desafios, conclua a rodada e veja sua posição real no ranking.",
    openGame: "Jogar",
    activeGame: "Arena ativa",
    closeGame: "Fechar arena",
    restartGame: "Reiniciar rodada",
    switchGame: "Trocar jogo",
    controls: "Controles",
    bestScore: "Melhor score",
    position: "Posição",
    noScore: "Ainda não jogado",
    noScoreShort: "—",
    focusEyebrow: "MODO FOCO",
    focusHint: "O score é enviado ao concluir a rodada. Apenas seu melhor resultado define sua posição.",
    submitting: "Registrando resultado...",
    submitted: "Resultado registrado",
    submitFailed: "Score local mantido. Tente novamente em outra rodada.",
    rankingEyebrow: "RANKING REAL",
    rankingTitle: "Top 3 e sua posição.",
    rankingText: "O Top 3 mostra apenas scores persistidos. Sua posição individual continua visível mesmo fora dos primeiros lugares.",
    topPlayers: "Top 3",
    liveRanking: "LIVE",
    realRanking: "DADOS REAIS",
    yourResult: "Seu resultado",
    rankExplanation: "Sua posição é calculada no ranking completo da arena, não apenas entre os três resultados exibidos acima.",
    loading: "Carregando dados reais do Arcade...",
    partial: "Parte do ranking está temporariamente indisponível. Os jogos continuam ativos.",
    loadError: "Não foi possível carregar os dados do ranking. Os jogos continuam disponíveis.",
    emptyRanking: "Ainda não há scores reais registrados nesta arena.",
    rankPrefix: "#",
    retry: "Tentar novamente",
    aliasGateEyebrow: "ANTES DE JOGAR",
    aliasGateTitle: "Escolha seu alias",
    aliasGateText: "Seu alias será usado para registrar sua pontuação e posição antes de abrir",
    aliasEditText: "Atualize o nome que identifica seus resultados no Developer Arcade.",
    aliasGateHint: "Use um nome curto e reconhecível. Ele poderá ser alterado depois.",
    aliasGateContinue: "Salvar e jogar",
    aliasGateSave: "Salvar alias",
    aliasGateCancel: "Agora não",
    transitionEyebrow: "PREPARANDO ARCADE",
    loadingAlias: "Abrindo identificação do jogador...",
    savingPlayer: "Salvando seu jogador...",
    loadingGame: "Carregando arena",
    loadingGameReady: "Jogador confirmado. Preparando arena",
  },
  en: {
    eyebrow: "DEVELOPER ARCADE",
    title: "Developer Arcade",
    intro: "Four quick arenas to test logic, reflexes, and consistency.",
    live: "Arcade online",
    persistent: "Best score saved",
    uniqueRanking: "Player-based ranking",
    playerEyebrow: "YOUR PLAYER",
    playerTitle: "Arcade profile",
    playerText: "Your alias identifies your results across all four arenas.",
    aliasLabel: "Alias",
    aliasPlaceholder: "E.g. Álvaro Dev",
    saveAlias: "Save",
    savingAlias: "Saving...",
    aliasSaved: "Alias updated.",
    aliasError: "The alias could not be updated right now.",
    aliasRequired: "Enter an alias to continue.",
    anonymous: "AN",
    noAlias: "Alias not set",
    editAlias: "Edit",
    setAlias: "Set alias",
    sessionScore: "Session score",
    completedGames: "Completed games",
    bestPosition: "Best position",
    gamesEyebrow: "ARENAS",
    gamesTitle: "Choose an arena.",
    gamesText: "Enter one of four challenges, finish the round, and see your real leaderboard position.",
    openGame: "Play",
    activeGame: "Active arena",
    closeGame: "Close arena",
    restartGame: "Restart run",
    switchGame: "Switch game",
    controls: "Controls",
    bestScore: "Best score",
    position: "Position",
    noScore: "Not played yet",
    noScoreShort: "—",
    focusEyebrow: "FOCUS MODE",
    focusHint: "Your score is submitted when the round ends. Only your best result defines your position.",
    submitting: "Saving result...",
    submitted: "Result saved",
    submitFailed: "Local score kept. Try again in another round.",
    rankingEyebrow: "REAL RANKING",
    rankingTitle: "Top 3 and your position.",
    rankingText: "The Top 3 contains persisted scores only. Your individual position remains visible even outside the leading places.",
    topPlayers: "Top 3",
    liveRanking: "LIVE",
    realRanking: "REAL DATA",
    yourResult: "Your result",
    rankExplanation: "Your position is calculated against the complete arena ranking, not only the three results displayed above.",
    loading: "Loading real Arcade data...",
    partial: "Part of the ranking is temporarily unavailable. The games remain active.",
    loadError: "Ranking data could not be loaded. The games remain available.",
    emptyRanking: "No real scores have been registered in this arena yet.",
    rankPrefix: "#",
    retry: "Try again",
    aliasGateEyebrow: "BEFORE YOU PLAY",
    aliasGateTitle: "Choose your alias",
    aliasGateText: "Your alias will identify your score and position before opening",
    aliasEditText: "Update the name used to identify your results in the Developer Arcade.",
    aliasGateHint: "Use a short recognizable name. You can change it later.",
    aliasGateContinue: "Save and play",
    aliasGateSave: "Save alias",
    aliasGateCancel: "Not now",
    transitionEyebrow: "PREPARING ARCADE",
    loadingAlias: "Opening player identity...",
    savingPlayer: "Saving your player...",
    loadingGame: "Loading arena",
    loadingGameReady: "Player confirmed. Preparing arena",
  },
} as const;
